config/routes.rb
Rails.application.routes.draw do
  get 'behaviours/index'

  resources :behaviours do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'behaviours#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/behaviour.rb
class Behaviour < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :behaviour
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/behaviours_controller.rb
class BehavioursController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @behaviour = Behaviour.all
  end

  def show
    @behaviour = Behaviour.find(params[:id])
  end

  def new
    @behaviour = Behaviour.new
  end

  def edit
    @behaviour = Behaviour.find(params[:id])
  end

  def create
    @behaviour = Behaviour.new(behaviour_params)

    if @behaviour.save
      redirect_to @behaviour
    else
      render 'new'
    end
  end

  def update
    @behaviour = Behaviour.find(params[:id])

    if @behaviour.update(behaviour_params)
      redirect_to @behaviour
    else
      render 'edit'
    end
  end

  def destroy
    @behaviour = Behaviour.find(params[:id])
    @behaviour.destroy

    redirect_to behaviours_path
  end

  private
    def behaviour_params
      params.require(:behaviour).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @behaviour = Behaviour.find(params[:behaviour_id])
    @comment = @behaviour.comments.create(comment_params)
    redirect_to behaviour_path(@behaviour)
  end

  def destroy
    @behaviour = Behaviour.find(params[:behaviour_id])
    @comment = @behaviour.comments.find(params[:id])
    @comment.destroy
    redirect_to behaviour_path(@behaviour)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/behaviours_helper.rb
module BehavioursHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/behaviours/_form.html.erb
<%= form_with model: @behaviour, local: true do |form| %>

  <% if @behaviour.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@behaviour.errors.count, "error") %> prohibited
        this behaviour from being saved:
      </h2>
      <ul>
        <% @behaviour.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/behaviours/edit.html.erb
<h1>Edit Behaviour</h1>

<%= render 'form' %>

<%= link_to 'Back', behaviours_path %>

app/views/behaviours/index.html.erb
<center>
  <head>
    <link rel="shortcut icon" href="/public/favicon.ico"/>
<h1> DailyChange </h1>

</head>
<br>
<center>
<h2> Hello and welcome to the DailyChange space - how are you going to make a difference?
  </h2>
  <%= form_with scope: :behaviour, url: behaviours_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
<br>
<br>

  <h2>Actions so far:</h2>
<br>
  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="2"></th>
    </tr>

    <% @behaviour.each do |behaviour| %>
      <tr>
        <td><%= behaviour.title %></td>
        <td><%= behaviour.text %></td>
        <td><%= link_to 'Show', behaviour_path(behaviour) %></td>
        <td><%= link_to 'Edit', edit_behaviour_path(behaviour) %></td>
        <td><%= link_to 'Delete', behaviour_path(behaviour),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= link_to 'New behaviour', new_behaviour_path %>
  </table>

app/views/behaviours/new.html.erb
<h1>New Behaviour</h1>

<%= form_with scope: :behaviour, url: behaviours_path, local: true do |form| %>

<% if @behaviour.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@behaviour.errors.count, "error") %>
    prohibited this behaviour from being saved:
    </h2>
    <ul>
      <% @behaviour.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
      </div>
      <% end %>

      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        </p>

        <p>
          <%= form.label :text %><br>
          <%= form.text_area :text %>
          </p>

          <p>
            <%= form.submit %>
            </p>

<% end %>

<%= link_to 'Back', behaviours_path %>

app/views/behaviours/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @behaviour.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @behaviour.text %>
</p>

<h2>Comments</h2>
<%= render @behaviour.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_behaviour_path(@behaviour) %> |
<%= link_to 'Back', behaviours_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter name:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.behaviour, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @behaviour, @behaviour.comments.build ],
local: true) do |form| %>
<p>
  <%= form.label :commenter %><br>
  <%= form.text_field :commenter %>
</p>
<p>
  <%= form.label :body %><br>
  <%= form.text_area :body %>
</p>
<p>
  <%= form.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
  <head>
    <title>Dailychange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

<footer>
  <div class="container">
    <%= Time.now %>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">The Change Making App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/behaviours">Behaviours</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Description of new behaviour', controller: 'behaviours' %>
<!-- <p>Find me in app/views/welcome/index.html.erb</p> -->